### ISSUE TITLE
Change gear icon to FA character (fa-cog)

### ISSUE THREAD

**Issue by thomasnguyen** [belcurv/meerkat_momentum#8]
In progress by @thomasnguyen

**Comment by thomasnguyen** [comment]
Finished. Should be without bugs. Feel free to create or reopen the issue if there are bugs.

**Comment by belcurv** [comment]
In FF (I don't have chrome at work) there are a few pixels between the bottom border and the bottom edge of the viewport.

![two_pixels](https://cloud.githubusercontent.com/assets/17347977/22388515/8061cd32-e4a6-11e6-89b9-4d0cc8a5fb21.png)

**Comment by belcurv** [comment]
Looks good @thomasnguyen , closing the issue
